runtime: custom
env: flex
service: matlab

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20

skip_files:
  - .idea
  - .mvn
  - src
  - target
  - .gitignore
  - gs-rest-service.iml
  - appengine-matlab-service.iml
  - LICENSE
  - mvnw
  - mvnw.cmd
  - pom.xml
  - README.md