runtime: custom
env: flex
service: matlab

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20

#automatic_scaling:
#  max_num_instances: 1

manual_scaling:
  instances: 1

health_check:
#  enable_health_check: False
  check_interval_sec: 10
  timeout_sec: 5
  unhealthy_threshold: 10
  healthy_threshold: 1

skip_files:
  - .idea
  - .mvn
  - src
  - target
  - .gitignore
  - gs-rest-service.iml
  - appengine-matlab-service.iml
  - LICENSE
  - mvnw
  - mvnw.cmd
  - pom.xml
  - README.md
  - .git
  - lib
  - .travis.yml
  - app.yaml
  - travis-cigrowbit-52554fcb00cd.json
  - travis-cigrowbit-52554fcb00cd.json.enc